apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::971422717446:user/sainatha.yatham@gmail.com
      username: admin
      groups:
        - system:masters

