apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.0.0
    chart: argo-cd
    helm:
      values: |
        configs:
          params:
            server.insecure: true
        server:
          service:
            type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

