#!/bin/bash

# Script to push Kubernetes manifests to a separate branch for Argo CD
# Usage: ./scripts/push-manifests-to-branch.sh

set -e

BRANCH_NAME="k8s-manifests"
K8S_DIR="k8s"
ARGOCD_DIR="argocd"

echo "🚀 Pushing Kubernetes manifests to branch: $BRANCH_NAME"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)
echo "📍 Current branch: $CURRENT_BRANCH"

# Check if k8s directory exists
if [ ! -d "$K8S_DIR" ]; then
    echo "❌ Error: $K8S_DIR directory not found"
    exit 1
fi

# Check if argocd directory exists
if [ ! -d "$ARGOCD_DIR" ]; then
    echo "⚠️  Warning: $ARGOCD_DIR directory not found, creating it"
    mkdir -p "$ARGOCD_DIR"
fi

# Check if branch exists
if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
    echo "📦 Branch $BRANCH_NAME already exists, checking it out"
    git checkout $BRANCH_NAME
    git pull origin $BRANCH_NAME 2>/dev/null || true
else
    echo "🌿 Creating new branch: $BRANCH_NAME"
    git checkout -b $BRANCH_NAME
fi

# Remove existing k8s and argocd directories if they exist
if [ -d "$K8S_DIR" ]; then
    echo "🧹 Cleaning up existing $K8S_DIR directory"
    rm -rf "$K8S_DIR"
fi

if [ -d "$ARGOCD_DIR" ]; then
    echo "🧹 Cleaning up existing $ARGOCD_DIR directory"
    rm -rf "$ARGOCD_DIR"
fi

# Copy k8s directory from main branch
echo "📋 Copying Kubernetes manifests from main branch"
git checkout $CURRENT_BRANCH -- $K8S_DIR

# Copy argocd directory from main branch if it exists
if [ -d "$ARGOCD_DIR" ]; then
    echo "📋 Copying Argo CD manifests from main branch"
    git checkout $CURRENT_BRANCH -- $ARGOCD_DIR 2>/dev/null || true
fi

# Stage all changes
git add $K8S_DIR $ARGOCD_DIR

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo "✅ No changes to commit"
else
    # Commit changes
    echo "💾 Committing changes"
    git commit -m "chore: update Kubernetes manifests for Argo CD deployment

- Updated Kubernetes manifests
- Updated Argo CD application configurations
- Auto-generated by push-manifests-to-branch.sh"

    # Push to remote
    echo "📤 Pushing to remote repository"
    git push origin $BRANCH_NAME

    echo "✅ Successfully pushed manifests to branch: $BRANCH_NAME"
fi

# Return to original branch
echo "🔄 Returning to original branch: $CURRENT_BRANCH"
git checkout $CURRENT_BRANCH

echo "✨ Done! Manifests are available in branch: $BRANCH_NAME"
echo "🔗 Argo CD will sync from: https://github.com/YOUR_USERNAME/Z2RWander.git (branch: $BRANCH_NAME)"

